[workspace]
members = ["app", "common", "engine", "ui"]
resolver = "3"

[workspace.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }
