[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "engine"
path = "lib.rs"

[[bin]]
name = "pack_sandbox"
path = "pack_sandbox.rs"

[dependencies]
bytemuck.workspace = true
crossbeam-queue.workspace = true
glam.workspace = true
glyphon.workspace = true
image.workspace = true
indexmap.workspace = true
mlua.workspace = true
naga.workspace = true
rand.workspace = true
rapidhash.workspace = true
raw-window-handle.workspace = true
rustfft.workspace = true
semver.workspace = true
serde.workspace = true
smol.workspace = true
thiserror.workspace = true
toml.workspace = true
wasapi.workspace = true
wgpu.workspace = true
cbor2 .workspace = true
libloading.workspace = true
chrono.workspace = true
zip.workspace = true

ui.path = "../ui"
wgsl-shaders = { path = "../wallpapers/wgsl" }


[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
