[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "engine"
path = "lib.rs"

[dependencies]
bytemuck.workspace = true
rand.workspace = true
smol.workspace = true
raw-window-handle.workspace = true
vello.workspace = true
wasapi.workspace = true
rustfft.workspace = true
image.workspace = true

ui.path = "../ui"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
