[package]
name = "technoir"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "technoir"
path = "main.rs"

[dependencies]
smol.workspace = true
raw-window-handle.workspace = true
vello.workspace = true

common.path = "../common"
engine.path = "../engine"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[build-dependencies]
winresource = "0.1.31"
